name: "Build OnlyOffice"
on:
  workflow_dispatch: # on button click

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/truecharts/nonlyoffice-build:latest
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2
        name: Checkout
        with:
          token: ${{ secrets.BOT_TOKEN }}
      - name: "Build binaries"
        run: |
          cd "/build_tools/tools/linux"
          python3 ./automate.py server
          ls "/build_tools/out"
      - name: "Build Package"
        run: |
          cd /
          git clone https://github.com/ONLYOFFICE/document-server-package.git
          cd document-server-package/deb
          apt build-dep ./
          cd /document-server-package
          # Workaround for my system where uname -p says: unknown
          # sed -i 's/TARGET := $(PLATFORM)_$(ARCHITECTURE)/TARGET := $(PLATFORM)_64/g' Makefile
          # Workaround to avoid ending with an error
          sed -i 's/--changes-option=-u./--changes-option=-u. --buildinfo-option=-u./g' Makefile
          make deb
      - name: "Move binaries to repo"
        run: |
          mv "/document-server-package/deb" "${GITHUB_WORKSPACE}/bin"
      - name: "Push binaries to repo"
        run: |
          cd ${GITHUB_WORKSPACE}
          git config user.name "TrueCharts-Bot"
          git config user.email "bot@truecharts.org"
          git add --all
          git commit -sm "Commit new binaries" || exit 0
          git push
