name: "Build OnlyOffice"
on:
  push:
    branches:
      - 'main'
    tags-ignore:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/truecharts/nonlyoffice-build:latest
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2
        name: Checkout
        with:
          token: ${{ secrets.BOT_TOKEN }}
      - name: Set variables
        run: |
          VER=$(cat VERSION)
          echo "VERSION=$VER" >> $GITHUB_ENV
          BLD=$(cat BUILD)
          echo "BUILD=$BLD" >> $GITHUB_ENV
      - name: "Build binaries"
        env:
          PRODUCT_VERSION: '${{ env.VERSION }}'
          BUILD_NUMBER: '${{ env.BUILD }}'
          NODE_ENV: 'production'
        run: |
          cd "/build_tools/tools/linux"
          python3 ./automate.py server
          ls "/build_tools/out"
      - name: "Build Package"
        env:
          PRODUCT_VERSION: '${{ env.VERSION }}'
          BUILD_NUMBER: 'truecharts'
        run: |
          cd /document-server-package
          # Workaround to avoid ending with an error
          sed -i 's/--changes-option=-u./--changes-option=-u. --buildinfo-option=-u./g' Makefile
          make deb
          ls /document-server-package/deb
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.BOT_TOKEN }}"
          automatic_release_tag: "v${{ env.VERSION }}"
          files: |
            /document-server-package/deb/*.deb
