name: "Build OnlyOffice"
on:
  workflow_dispatch: # on button click

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/truecharts/nonlyoffice-build:latest
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2
        name: Checkout
        with:
          token: ${{ secrets.BOT_TOKEN }}
      - name: "Build binaries"
        run: |
          cd "/build_tools/tools/linux"
          python3 ./automate.py server
          ls "/build_tools/out"
      - name: "Move binaries to repo"
        run: |
          mv "/build_tools/out" "${GITHUB_WORKSPACE}/bin"
          cd "${GITHUB_WORKSPACE}/bin"
          find . -name ".git" -type f -print0 | xargs -0 /bin/rm -f
          find . -name "*.git" -type f -print0 | xargs -0 /bin/rm -f
      - name: "Push binaries to repo"
        run: |
          cd ${GITHUB_WORKSPACE}
          git config user.name "TrueCharts-Bot"
          git config user.email "bot@truecharts.org"
          git add --all
          git commit -sm "Commit new binaries" || exit 0
          git push
